---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: "v3.3.0"
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier.git
    rev: "d0f1c0ddb04e215d2a92eb0e0de977b236d79f7d"
    hooks:
      - id: prettier
        name: "Apply Code Formatting"
