---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: "v4.0.0"
    hooks:
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-xml
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier.git
    rev: "v2.3.0"
    hooks:
      - id: prettier
        name: "Apply Code Formatting"
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: "1.4.0"
    hooks:
      - id: php-lint
